apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- flux-system
#- ../apps/
#- base/repo.yaml
#- base/metrics-server.yaml
#- base/cert-manager.yaml
#- base/cert-manager-issuers.yaml
#- base/monitoring.yaml
#- base/monitoring-config.yaml
#- base/logging.yaml
#- base/tempo.yaml
#- base/otel-operator.yaml
#- base/otel-config.yaml
#- base/otel-demo.yaml
#- base/ingress-nginx.yaml
#- base/aws-efs-storageclass.yaml
#- base/aws-load-balancer-controller.yaml
#- base/aws-external-secrets-operator.yaml
#- base/aws-external-secrets-config.yaml
#- base/ecr-credentials-sync.yaml
#- base/flagger.yaml
#- base/teleport.yaml
#- base/opencost.yaml ## Experimental

#patches:
#- path: overlay/cert-manager.yaml
#- path: overlay/cert-manager-issuers.yaml
#- path: overlay/monitoring.yaml
#- path: overlay/monitoring-logging.yaml
#- path: overlay/monitoring-tempo.yaml
#- path: overlay/logging.yaml
#- path: overlay/otel-operator.yaml
#- path: overlay/aws-load-balancer-controller.yaml
#- path: overlay/aws-external-secrets-operator.yaml
#- path: overlay/aws-external-secrets-config.yaml
#- path: overlay/ecr-credentials-sync.yaml
#- path: overlay/flagger.yaml
#- path: overlay/teleport.yaml
#- path: overlay/tempo.yaml
#- path: overlay/opencost.yaml ## Experimental

#patchesJson6902:
#- path: overlay/monitoring-tempo-ops.yaml
#  target:
#    group: helm.toolkit.fluxcd.io
#    version: v2
#    kind: HelmRelease
#    name: monitoring
#    namespace: flux-system
