apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  chart:
    spec:
      chart: templater
      sourceRef:
        kind: HelmRepository
        name: getupcloud
      version: "~> 1.2"
  dependsOn:
  - name: external-secrets
  install:
    createNamespace: false
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 10m
  releaseName: external-secrets-config
  storageNamespace: external-secrets
  targetNamespace: external-secrets
  values:
    template-store:
      apiVersion: external-secrets.io/v1beta1
      kind: ClusterSecretStore
      metadata:
        namespace: external-secrets
      spec:
        provider:
          aws:
            service: SecretsManager
            auth:
              jwt:
                serviceAccountRef:
                  name: external-secrets
                  namespace: external-secrets
